# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producter',
            field=models.CharField(max_length=200, null=True, verbose_name='\u4ea7\u54c1\u8d1f\u8d23\u4eba'),
        ),
    ]
