# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=64, verbose_name='\u7cfb\u7edf\u540d\u79f0')),
                ('setvalue', models.CharField(max_length=200, verbose_name='\u7cfb\u7edf\u8bbe\u503c')),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u8bbe\u7f6e',
                'verbose_name_plural': '\u7cfb\u7edf\u8bbe\u7f6e',
            },
        ),
    ]
