# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-17 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20190507_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcasename', models.CharField(max_length=200, verbose_name='\u7528\u4f8b\u540d\u79f0')),
                ('webtestresult', models.BooleanField(verbose_name='\u6d4b\u8bd5\u7ed3\u679c')),
                ('webtester', models.CharField(max_length=16, verbose_name='\u6d4b\u8bd5\u8d1f\u8d23\u4eba')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'web\u6d4b\u8bd5\u7528\u4f8b',
                'verbose_name_plural': 'web\u6d4b\u8bd5\u7528\u4f8b',
            },
        ),
        migrations.CreateModel(
            name='Webcasestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webteststep', models.CharField(max_length=200, verbose_name='\u6d4b\u8bd5\u6b65\u805a')),
                ('webtestobjname', models.CharField(max_length=200, verbose_name='\u6d4b\u8bd5\u5bf9\u8c61\u540d\u79f0\u63cf\u8ff0')),
                ('webfindmethod', models.CharField(max_length=200, verbose_name='\u5b9a\u4f4d\u65b9\u5f0f')),
                ('webevelement', models.CharField(max_length=800, verbose_name='\u63a7\u4ef6\u5143\u7d20')),
                ('weboptmethod', models.CharField(max_length=200, verbose_name='\u64cd\u4f5c\u65b9\u6cd5')),
                ('webtestdata', models.CharField(max_length=200, null=True, verbose_name='\u6d4b\u8bd5\u6570\u636e')),
                ('webassertdata', models.CharField(max_length=200, verbose_name='\u9a8c\u8bc1\u6570\u636e')),
                ('webtestresult', models.BooleanField(verbose_name='\u6d4b\u8bd5\u7ed3\u679c')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('Webcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Webcase')),
            ],
        ),
    ]
