# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-23 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('apitest', '0002_auto_20190419_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=100, verbose_name='\u63a5\u53e3\u540d\u79f0')),
                ('apiurl', models.CharField(max_length=200, verbose_name='url\u5730\u5740')),
                ('apiparamvalue', models.CharField(max_length=16, verbose_name='\u8bf7\u6c42\u53c2\u6570\u548c\u503c')),
                ('apimethod', models.CharField(choices=[('0', 'get'), ('1', 'post'), ('2', 'put')], default='0', max_length=200, null=True, verbose_name='\u8bf7\u6c42\u65b9\u6cd5')),
                ('apiresult', models.CharField(max_length=200, verbose_name='\u9884\u671f\u7ed3\u679c')),
                ('apistatus', models.BooleanField(verbose_name='\u662f\u5426\u901a\u8fc7')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': '\u5355\u4e00\u573a\u666f\u63a5\u53e3',
                'verbose_name_plural': '\u5355\u4e00\u573a\u666f\u63a5\u53e3',
            },
        ),
    ]
